import '@/styles/globals.css';
import '@aws-amplify/ui-react/styles.css';
import type { AppProps } from 'next/app';
import { useEffect } from 'react';
import { useRouter } from 'next/router';
import { DM_Sans } from 'next/font/google';
import { AppCacheProvider } from '@mui/material-nextjs/v14-pagesRouter';
import CssBaseline from '@mui/material/CssBaseline';
import GlobalStyles from '@mui/material/GlobalStyles';
import { ThemeProvider } from '@mui/material/styles';
import { appTheme } from '@/lib/theme';
import { Amplify, type ResourcesConfig } from 'aws-amplify';
import amplifyOutputs from '../../amplify_outputs.json';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import ErrorBoundary, {
  RootErrorBoundary,
  RouteErrorBoundary,
} from '@/components/ErrorBoundary';
import { ToastProvider } from '@/components/Toast';
import { AuthProvider, useAuth } from '@/contexts/AuthContext';
import { RBACProvider } from '@/contexts/RBACContext';
import { TenantProvider } from '@/features/tenant';
import { resolveProfileFromCognitoGroups } from '@/rbac';
import '@/lib/i18n'; // Initialize i18n
import { useTranslation } from 'react-i18next';
export { reportWebVitals } from '@/lib/webVitals';

// ─── Font ───────────────────────────────────────────────────────────────────────
// Self-hosted by next/font; exposed as --font-body so tokens.typography.fontFamily
// resolves to it everywhere, including MUI portals rendered outside the app root.

const dmSans = DM_Sans({
  subsets: ['latin', 'latin-ext'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
});

// ─── Amplify configuration ─────────────────────────────────────────────────────
// Configured synchronously at module load so that AuthProvider's session check
// (a child effect, which runs BEFORE parent effects) always sees a configured
// Amplify. amplify_outputs.json is generated by `ampx pipeline-deploy` on
// Amplify builds and committed as a stub for local/CI builds.
// `ssr: true` keeps tokens in cookies so server-side code could read them later.

Amplify.configure(amplifyOutputs as ResourcesConfig, { ssr: true });

// ─── Auth → RBAC Bridge ────────────────────────────────────────────────────────

/**
 * Reads the authenticated user's Cognito groups and maps them to the
 * appropriate RBAC profile, providing entitlements to the whole subtree.
 * When no user is logged in, an empty entitlement set is provided.
 */
function AuthenticatedRBACProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  const { user } = useAuth();
  const profile = user
    ? (resolveProfileFromCognitoGroups(user.groups) ?? undefined)
    : undefined;

  return <RBACProvider profile={profile}>{children}</RBACProvider>;
}

function SkipLink() {
  const { t } = useTranslation('shell');
  return (
    <a href='#main-content' className='skip-link'>
      {t('skipToContent')}
    </a>
  );
}

// ─── React Query Client ────────────────────────────────────────────────────────

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 30 * 1000,
      retry: 3,
      retryDelay: (attemptIndex: number) =>
        Math.min(1000 * 2 ** attemptIndex, 30000),
      refetchOnWindowFocus: true,
      refetchOnReconnect: true,
    },
    mutations: {
      retry: 1,
    },
  },
});

// ─── App Component ─────────────────────────────────────────────────────────────

export default function App(props: AppProps) {
  const { Component, pageProps } = props;
  const router = useRouter();

  // Track page views (integrate with your analytics provider)
  useEffect(() => {
    const handleRouteChange = (_url: string) => {
      // Analytics tracking placeholder
      // Example: trackPageView(url);
    };

    router.events.on('routeChangeComplete', handleRouteChange);
    return () => {
      router.events.off('routeChangeComplete', handleRouteChange);
    };
  }, [router.events]);

  return (
    <AppCacheProvider {...props}>
      <ThemeProvider theme={appTheme} defaultMode='system'>
        <CssBaseline enableColorScheme />
        <GlobalStyles
          styles={{ ':root': { '--font-body': dmSans.style.fontFamily } }}
        />
        <RootErrorBoundary>
          <AuthProvider>
            <AuthenticatedRBACProvider>
              <QueryClientProvider client={queryClient}>
                <TenantProvider>
                  <ErrorBoundary level='app'>
                    <ToastProvider>
                      <SkipLink />
                      <RouteErrorBoundary>
                        <Component {...pageProps} />
                      </RouteErrorBoundary>
                    </ToastProvider>
                  </ErrorBoundary>
                </TenantProvider>
              </QueryClientProvider>
            </AuthenticatedRBACProvider>
          </AuthProvider>
        </RootErrorBoundary>
      </ThemeProvider>
    </AppCacheProvider>
  );
}
